## **Import Libraries**

In [10]:
#Insall all the library 
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import seaborn as sns

### Read the data

In [11]:
df=pd.read_excel("RiyadhHotelBooking.xlsx")

In [12]:
df

,Unnamed: 0.1,Unnamed: 0,URLS,City,Title,Price,RoomType,Check_in,Check_Out,Rate,Address,latlon,Score
0,0,0,https://www.booking.com/hotel/sa/golden-dune.a...,الرياض,جولدن ديون هوتل & سويت,US$96,غرفة سوبيريور مزدوجة,2022-09-03,2022-09-04,['3 out of 5'],"['\n شارع سعود العثمان سعود سعود العثمان سعود,...","24.68825273,46.80286766",['\n8.1\n']
1,1,1,https://www.booking.com/hotel/sa/fndq-lbyrl-la...,الرياض,فندق لابيرلا,US$75,غرفة توأم مع حمام خاص,2022-09-03,2022-09-04,['3 out of 5'],"['\nفندق لابيرلا, 13216 الرياض, المملكة العربي...","24.79451790,46.81846073",['\n7.3\n']
2,2,2,https://www.booking.com/hotel/sa/krm-lryd-kare...,الرياض,فندق كارم الرياض Karim Hotel Riyadh,US$93,غرفة قياسية مزدوجة,2022-09-03,2022-09-04,['4 out of 5'],"['\nPrince Mugrin Ibn Abdulaziz, An Nuzhah Dis...","24.75476486,46.70609703",['\n8.6\n']
3,3,3,https://www.booking.com/hotel/sa/al-fahd-suite...,"العليا, الرياض",Carawan Hotel Olaya - فندق كروان العليا,US$66,غرفة مزدوجة مع حوض استحمام,2022-09-03,2022-09-04,NaN,NaN,NaN,NaN
4,4,4,https://www.booking.com/hotel/sa/myn-lmlq-107....,الرياض,Almakan Hotel 113,US$46,استوديو,2022-09-03,2022-09-04,['3 out of 5'],"['\nKing Fahd Road العمرة -الملقا, 13521 الريا...","24.66230438,46.70117478",['\n6.6\n']
...,...,...,...,...,...,...,...,...,...,...,...,...,...
164661,164661,164661,https://www.booking.com/hotel/sa/kease-d12-al-...,الرياض,Kease D12 Al Qirwan Apartment,US$280,شقة بغرفتي نوم,2023-09-01,2023-09-02,NaN,NaN,NaN,NaN
164662,164662,164662,https://www.booking.com/hotel/sa/kease-c4-alna...,الرياض,Kease C4 Alnafel Vip,US$249,شقة بـ3 غرف نوم,2023-09-01,2023-09-02,NaN,NaN,NaN,NaN
164663,164663,164663,https://www.booking.com/hotel/sa/residential-a...,الرياض,Kease J9 Al Arid Black Diamond - العارض الالما...,US$409,شقة بـ3 غرف نوم,2023-09-01,2023-09-02,['4 out of 5'],"['\nشارع عبدالله بن العاص, 13338 الرياض, الممل...","24.88341681,46.62883952",['\n10\n']
164664,164664,164664,https://www.booking.com/hotel/sa/kease-a13-ala...,الرياض,Kease A13 AlArid Black Diamond,US$275,شقة بـ3 غرف نوم,2023-09-01,2023-09-02,NaN,NaN,NaN,NaN
164665,164665,164665,https://www.booking.com/hotel/sa/kesae-malqa-b...,الرياض,Kesae Malqa B3 Wakan,US$308,شقة بـ3 غرف نوم,2023-09-01,2023-09-02,NaN,NaN,NaN,NaN

In [13]:
df.head()

,Unnamed: 0.1,Unnamed: 0,URLS,City,Title,Price,RoomType,Check_in,Check_Out,Rate,Address,latlon,Score
0,0,0,https://www.booking.com/hotel/sa/golden-dune.a...,الرياض,جولدن ديون هوتل & سويت,US$96,غرفة سوبيريور مزدوجة,2022-09-03,2022-09-04,['3 out of 5'],"['\n شارع سعود العثمان سعود سعود العثمان سعود,...","24.68825273,46.80286766",['\n8.1\n']
1,1,1,https://www.booking.com/hotel/sa/fndq-lbyrl-la...,الرياض,فندق لابيرلا,US$75,غرفة توأم مع حمام خاص,2022-09-03,2022-09-04,['3 out of 5'],"['\nفندق لابيرلا, 13216 الرياض, المملكة العربي...","24.79451790,46.81846073",['\n7.3\n']
2,2,2,https://www.booking.com/hotel/sa/krm-lryd-kare...,الرياض,فندق كارم الرياض Karim Hotel Riyadh,US$93,غرفة قياسية مزدوجة,2022-09-03,2022-09-04,['4 out of 5'],"['\nPrince Mugrin Ibn Abdulaziz, An Nuzhah Dis...","24.75476486,46.70609703",['\n8.6\n']
3,3,3,https://www.booking.com/hotel/sa/al-fahd-suite...,"العليا, الرياض",Carawan Hotel Olaya - فندق كروان العليا,US$66,غرفة مزدوجة مع حوض استحمام,2022-09-03,2022-09-04,NaN,NaN,NaN,NaN
4,4,4,https://www.booking.com/hotel/sa/myn-lmlq-107....,الرياض,Almakan Hotel 113,US$46,استوديو,2022-09-03,2022-09-04,['3 out of 5'],"['\nKing Fahd Road العمرة -الملقا, 13521 الريا...","24.66230438,46.70117478",['\n6.6\n']

### Preprossing

In [14]:
#Droup unnecessary columns 
df=df.dropna(subset=['Rate'])
df=df.dropna(subset=['Score'])
df=df.drop(['Unnamed: 0.1','Unnamed: 0'], axis=1)
df

,URLS,City,Title,Price,RoomType,Check_in,Check_Out,Rate,Address,latlon,Score
0,https://www.booking.com/hotel/sa/golden-dune.a...,الرياض,جولدن ديون هوتل & سويت,US$96,غرفة سوبيريور مزدوجة,2022-09-03,2022-09-04,['3 out of 5'],"['\n شارع سعود العثمان سعود سعود العثمان سعود,...","24.68825273,46.80286766",['\n8.1\n']
1,https://www.booking.com/hotel/sa/fndq-lbyrl-la...,الرياض,فندق لابيرلا,US$75,غرفة توأم مع حمام خاص,2022-09-03,2022-09-04,['3 out of 5'],"['\nفندق لابيرلا, 13216 الرياض, المملكة العربي...","24.79451790,46.81846073",['\n7.3\n']
2,https://www.booking.com/hotel/sa/krm-lryd-kare...,الرياض,فندق كارم الرياض Karim Hotel Riyadh,US$93,غرفة قياسية مزدوجة,2022-09-03,2022-09-04,['4 out of 5'],"['\nPrince Mugrin Ibn Abdulaziz, An Nuzhah Dis...","24.75476486,46.70609703",['\n8.6\n']
4,https://www.booking.com/hotel/sa/myn-lmlq-107....,الرياض,Almakan Hotel 113,US$46,استوديو,2022-09-03,2022-09-04,['3 out of 5'],"['\nKing Fahd Road العمرة -الملقا, 13521 الريا...","24.66230438,46.70117478",['\n6.6\n']
5,https://www.booking.com/hotel/sa/tulip-inn-al-...,"الملاذ, الرياض",فندق ريف الملز إنترناشونال,US$36,غرفة مزدوجة أو توأم,2022-09-03,2022-09-04,['3 out of 5'],"['\nطريق الملك عبد العزيزخلف بنك سامبا , الملا...","24.65901078,46.72079802",['\n5.5\n']
...,...,...,...,...,...,...,...,...,...,...,...
164647,https://www.booking.com/hotel/sa/kease-a6-al-m...,الرياض,Kease A6 Al-Malqa Modern Royal Era,US$299,شقة بـ3 غرف نوم,2023-09-01,2023-09-02,['4 out of 5'],"['\n7856 ابحر, 13524 الرياض, المملكة العربية ا...","24.81915457,46.60549237",['\n10\n']
164649,https://www.booking.com/hotel/sa/al-tawan-b5-4...,الرياض,Kease B5-4 AlTawun Royal Touch - التعاون اللمس...,US$329,شقة بـ3 غرف نوم,2023-09-01,2023-09-02,['3 out of 5'],"['\n3858 العباس بن عبدالمطلب, 12476 الرياض, ال...","24.77499250,46.70473590",['\n6.7\n']
164657,https://www.booking.com/hotel/sa/a5-1-altawun-...,الرياض,Kease A5-1 Al Tawun Royal Touch - التعاون اللم...,US$329,شقة بـ3 غرف نوم,2023-09-01,2023-09-02,['4 out of 5'],"['\n3858 العباس بن عبدالمطلب, 12476 الرياض, ال...","24.77499250,46.70473590",['\n4.5\n']
164659,https://www.booking.com/hotel/sa/l-mt-b-swyts-...,الرياض,ال متعب سويتس الفلاح,US$64,استوديو,2023-09-01,2023-09-02,['3 out of 5'],"['\nطريق عثمان بن عفان, 13314 الرياض, المملكة ...","24.78986673,46.70271270",['\n7.7\n']
164663,https://www.booking.com/hotel/sa/residential-a...,الرياض,Kease J9 Al Arid Black Diamond - العارض الالما...,US$409,شقة بـ3 غرف نوم,2023-09-01,2023-09-02,['4 out of 5'],"['\nشارع عبدالله بن العاص, 13338 الرياض, الممل...","24.88341681,46.62883952",['\n10\n']

In [15]:
#Fill null value with coordinates
df.loc[df['Title'] == "شقة نيرفانا ريزدنس Nirvana Residence Apt", 'latlon'] = '24.833817422758095,46.6050683124813'

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 105668 entries, 0 to 164663
Data columns (total 11 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   URLS       105668 non-null  object
 1   City       105668 non-null  object
 2   Title      105668 non-null  object
 3   Price      105668 non-null  object
 4   RoomType   105668 non-null  object
 5   Check_in   105668 non-null  datetime64[ns]
 6   Check_Out  105668 non-null  datetime64[ns]
 7   Rate       105668 non-null  object
 8   Address    105668 non-null  object
 9   latlon     105668 non-null  object
 10  Score      105668 non-null  object
dtypes: datetime64[ns](2), object(9)
memory usage: 9.7+ MB

In [17]:
df.head()

,URLS,City,Title,Price,RoomType,Check_in,Check_Out,Rate,Address,latlon,Score
0,https://www.booking.com/hotel/sa/golden-dune.a...,الرياض,جولدن ديون هوتل & سويت,US$96,غرفة سوبيريور مزدوجة,2022-09-03,2022-09-04,['3 out of 5'],"['\n شارع سعود العثمان سعود سعود العثمان سعود,...","24.68825273,46.80286766",['\n8.1\n']
1,https://www.booking.com/hotel/sa/fndq-lbyrl-la...,الرياض,فندق لابيرلا,US$75,غرفة توأم مع حمام خاص,2022-09-03,2022-09-04,['3 out of 5'],"['\nفندق لابيرلا, 13216 الرياض, المملكة العربي...","24.79451790,46.81846073",['\n7.3\n']
2,https://www.booking.com/hotel/sa/krm-lryd-kare...,الرياض,فندق كارم الرياض Karim Hotel Riyadh,US$93,غرفة قياسية مزدوجة,2022-09-03,2022-09-04,['4 out of 5'],"['\nPrince Mugrin Ibn Abdulaziz, An Nuzhah Dis...","24.75476486,46.70609703",['\n8.6\n']
4,https://www.booking.com/hotel/sa/myn-lmlq-107....,الرياض,Almakan Hotel 113,US$46,استوديو,2022-09-03,2022-09-04,['3 out of 5'],"['\nKing Fahd Road العمرة -الملقا, 13521 الريا...","24.66230438,46.70117478",['\n6.6\n']
5,https://www.booking.com/hotel/sa/tulip-inn-al-...,"الملاذ, الرياض",فندق ريف الملز إنترناشونال,US$36,غرفة مزدوجة أو توأم,2022-09-03,2022-09-04,['3 out of 5'],"['\nطريق الملك عبد العزيزخلف بنك سامبا , الملا...","24.65901078,46.72079802",['\n5.5\n']

In [18]:
#Change the column type 
df['Checkin_day']=df['Check_in'].dt.day_name()
df['Checkout_day']=df['Check_Out'].dt.day_name()

In [19]:
#Change the type again to extract the day and month to new column 
df['Check_in']=df['Check_in'].astype(str)
df['Check_Out']=df['Check_Out'].astype(str)

In [20]:
#Spilt the column for check in and rename it  
split=df['Check_in'].str.split('-',expand=True)
df['Year']=split[0]
df['Month']=split[1]
df['Day']=split[2]

In [21]:
#Spilt the columne for check out and rename it 
split=df['Check_Out'].str.split('-',expand=True)
df['Year']=split[0]
df['Month']=split[1]
df['Day']=split[2]

In [22]:
#Change the column type to date time again 
df['Check_in']= pd.to_datetime(df['Check_in'])
df['Check_Out']= pd.to_datetime(df['Check_Out'])

In [23]:
#Change the column type for the month  
df['Check_Month']=df['Check_in'].dt.month_name()

In [24]:
#Spilt the lotlon in tow columne column 
split=df['latlon'].str.split(',',expand=True)
#Rename it 
df['lon']=split[0]
df['lat']=split[1]

In [25]:
#Split the Room type column
split=df['RoomType'].str.split(' ',expand=True)
df['Type']=split[0]

In [26]:
df.loc[df['Type'] == ' شقة', 'TYPE'] = 'شقة'
df.loc[df['Type'] == ' استوديو', 'TYPE'] = 'Studio'

In [27]:
#Catogry for the Type
df.loc[df['Type'] == "طماط", 'Type'] = "جناح"
df.loc[df['Type'] == "غرف", 'Type'] = "غرفة"
df.loc[df['Type'] == "قياسية", 'Type'] = "غرفة"
df.loc[df['Type'] == "قياسية،", 'Type'] = "غرفة"
df.loc[df['Type'] == "وحدة", 'Type'] = "غرفة"
df.loc[df['Type'] == "تنفيذية،", 'Type'] = "غرفة"
df.loc[df['Type'] == "وحدة", 'Type'] = "غرفة"
df.loc[df['Type'] == "Standard", 'Type'] = "غرفة"
df.loc[df['Type'] == "خيار", 'Type'] = "غرفة"
df.loc[df['Type'] == "كينغ", 'Type'] = "جناح"
df.loc[df['Type'] == "الجناح", 'Type'] = "جناح"
df.loc[df['Type'] == "شاليه", 'Type'] = "شاليه"
df.loc[df['Type'] == "سوبيريور", 'Type'] = "شاليه"
df.loc[df['Type'] == "فيلا", 'Type'] = "منزل"
df.loc[df['Type'] == "بيت", 'Type'] = "منزل"
df.loc[df['Type'] == "استديو", 'Type'] = "استوديو"
df.loc[df['Type'] == "ستوديو", 'Type'] = "استوديو"
# *****************************************************
df.loc[df['Type'] == "استديو", 'Type'] = "استوديو"
df.loc[df['Type'] == "ستوديو", 'Type'] = "استوديو"

In [28]:
df.loc[df['Type'] == 'استوديو', 'Type'] = 'Studio'
df.loc[df['Type'] == "شاليه", 'Type'] = 'Chalet'
df.loc[df['Type'] == "شقة", 'Type'] = 'Apartment'
df.loc[df['Type'] == "شاليه", 'Type'] = 'Chalet'
df.loc[df['Type'] == "منزل", 'Type'] = 'House'
df.loc[df['Type'] == "جناح", 'Type'] = 'Suite'
df.loc[df['Type'] == "غرفة", 'Type'] = 'Room'

In [29]:
#Drop the column  
df=df.drop(['RoomType'], axis=1)
df.head()

,URLS,City,Title,Price,Check_in,Check_Out,Rate,Address,latlon,Score,Checkin_day,Checkout_day,Year,Month,Day,Check_Month,lon,lat,Type,TYPE
0,https://www.booking.com/hotel/sa/golden-dune.a...,الرياض,جولدن ديون هوتل & سويت,US$96,2022-09-03,2022-09-04,['3 out of 5'],"['\n شارع سعود العثمان سعود سعود العثمان سعود,...","24.68825273,46.80286766",['\n8.1\n'],Saturday,Sunday,2022,09,04,September,24.68825273,46.80286766,Room,NaN
1,https://www.booking.com/hotel/sa/fndq-lbyrl-la...,الرياض,فندق لابيرلا,US$75,2022-09-03,2022-09-04,['3 out of 5'],"['\nفندق لابيرلا, 13216 الرياض, المملكة العربي...","24.79451790,46.81846073",['\n7.3\n'],Saturday,Sunday,2022,09,04,September,24.79451790,46.81846073,Room,NaN
2,https://www.booking.com/hotel/sa/krm-lryd-kare...,الرياض,فندق كارم الرياض Karim Hotel Riyadh,US$93,2022-09-03,2022-09-04,['4 out of 5'],"['\nPrince Mugrin Ibn Abdulaziz, An Nuzhah Dis...","24.75476486,46.70609703",['\n8.6\n'],Saturday,Sunday,2022,09,04,September,24.75476486,46.70609703,Room,NaN
4,https://www.booking.com/hotel/sa/myn-lmlq-107....,الرياض,Almakan Hotel 113,US$46,2022-09-03,2022-09-04,['3 out of 5'],"['\nKing Fahd Road العمرة -الملقا, 13521 الريا...","24.66230438,46.70117478",['\n6.6\n'],Saturday,Sunday,2022,09,04,September,24.66230438,46.70117478,Studio,NaN
5,https://www.booking.com/hotel/sa/tulip-inn-al-...,"الملاذ, الرياض",فندق ريف الملز إنترناشونال,US$36,2022-09-03,2022-09-04,['3 out of 5'],"['\nطريق الملك عبد العزيزخلف بنك سامبا , الملا...","24.65901078,46.72079802",['\n5.5\n'],Saturday,Sunday,2022,09,04,September,24.65901078,46.72079802,Room,NaN

In [30]:
df.Type.unique()

array(['Room', 'Studio', 'Apartment', 'Suite', 'Chalet', 'House', ''],
      dtype=object)

In [31]:
df

,URLS,City,Title,Price,Check_in,Check_Out,Rate,Address,latlon,Score,Checkin_day,Checkout_day,Year,Month,Day,Check_Month,lon,lat,Type,TYPE
0,https://www.booking.com/hotel/sa/golden-dune.a...,الرياض,جولدن ديون هوتل & سويت,US$96,2022-09-03,2022-09-04,['3 out of 5'],"['\n شارع سعود العثمان سعود سعود العثمان سعود,...","24.68825273,46.80286766",['\n8.1\n'],Saturday,Sunday,2022,09,04,September,24.68825273,46.80286766,Room,NaN
1,https://www.booking.com/hotel/sa/fndq-lbyrl-la...,الرياض,فندق لابيرلا,US$75,2022-09-03,2022-09-04,['3 out of 5'],"['\nفندق لابيرلا, 13216 الرياض, المملكة العربي...","24.79451790,46.81846073",['\n7.3\n'],Saturday,Sunday,2022,09,04,September,24.79451790,46.81846073,Room,NaN
2,https://www.booking.com/hotel/sa/krm-lryd-kare...,الرياض,فندق كارم الرياض Karim Hotel Riyadh,US$93,2022-09-03,2022-09-04,['4 out of 5'],"['\nPrince Mugrin Ibn Abdulaziz, An Nuzhah Dis...","24.75476486,46.70609703",['\n8.6\n'],Saturday,Sunday,2022,09,04,September,24.75476486,46.70609703,Room,NaN
4,https://www.booking.com/hotel/sa/myn-lmlq-107....,الرياض,Almakan Hotel 113,US$46,2022-09-03,2022-09-04,['3 out of 5'],"['\nKing Fahd Road العمرة -الملقا, 13521 الريا...","24.66230438,46.70117478",['\n6.6\n'],Saturday,Sunday,2022,09,04,September,24.66230438,46.70117478,Studio,NaN
5,https://www.booking.com/hotel/sa/tulip-inn-al-...,"الملاذ, الرياض",فندق ريف الملز إنترناشونال,US$36,2022-09-03,2022-09-04,['3 out of 5'],"['\nطريق الملك عبد العزيزخلف بنك سامبا , الملا...","24.65901078,46.72079802",['\n5.5\n'],Saturday,Sunday,2022,09,04,September,24.65901078,46.72079802,Room,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164647,https://www.booking.com/hotel/sa/kease-a6-al-m...,الرياض,Kease A6 Al-Malqa Modern Royal Era,US$299,2023-09-01,2023-09-02,['4 out of 5'],"['\n7856 ابحر, 13524 الرياض, المملكة العربية ا...","24.81915457,46.60549237",['\n10\n'],Friday,Saturday,2023,09,02,September,24.81915457,46.60549237,Apartment,NaN
164649,https://www.booking.com/hotel/sa/al-tawan-b5-4...,الرياض,Kease B5-4 AlTawun Royal Touch - التعاون اللمس...,US$329,2023-09-01,2023-09-02,['3 out of 5'],"['\n3858 العباس بن عبدالمطلب, 12476 الرياض, ال...","24.77499250,46.70473590",['\n6.7\n'],Friday,Saturday,2023,09,02,September,24.77499250,46.70473590,Apartment,NaN
164657,https://www.booking.com/hotel/sa/a5-1-altawun-...,الرياض,Kease A5-1 Al Tawun Royal Touch - التعاون اللم...,US$329,2023-09-01,2023-09-02,['4 out of 5'],"['\n3858 العباس بن عبدالمطلب, 12476 الرياض, ال...","24.77499250,46.70473590",['\n4.5\n'],Friday,Saturday,2023,09,02,September,24.77499250,46.70473590,Apartment,NaN
164659,https://www.booking.com/hotel/sa/l-mt-b-swyts-...,الرياض,ال متعب سويتس الفلاح,US$64,2023-09-01,2023-09-02,['3 out of 5'],"['\nطريق عثمان بن عفان, 13314 الرياض, المملكة ...","24.78986673,46.70271270",['\n7.7\n'],Friday,Saturday,2023,09,02,September,24.78986673,46.70271270,Studio,NaN
164663,https://www.booking.com/hotel/sa/residential-a...,الرياض,Kease J9 Al Arid Black Diamond - العارض الالما...,US$409,2023-09-01,2023-09-02,['4 out of 5'],"['\nشارع عبدالله بن العاص, 13338 الرياض, الممل...","24.88341681,46.62883952",['\n10\n'],Friday,Saturday,2023,09,02,September,24.88341681,46.62883952,Apartment,NaN

In [32]:
#Add a new column for Airport coordinates to calculate the distance  
df.insert(18, 'Airport', '24.9637, 46.7008')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 105668 entries, 0 to 164663
Data columns (total 21 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   URLS          105668 non-null  object
 1   City          105668 non-null  object
 2   Title         105668 non-null  object
 3   Price         105668 non-null  object
 4   Check_in      105668 non-null  datetime64[ns]
 5   Check_Out     105668 non-null  datetime64[ns]
 6   Rate          105668 non-null  object
 7   Address       105668 non-null  object
 8   latlon        105668 non-null  object
 9   Score         105668 non-null  object
 10  Checkin_day   105668 non-null  object
 11  Checkout_day  105668 non-null  object
 12  Year          105668 non-null  object
 13  Month         105668 non-null  object
 14  Day           105668 non-null  object
 15  Check_Month   105668 non-null  object
 16  lon           105668 non-null  object
 17  lat           105668 non-null  object
 18  Airport       105668 non-null  object
 19  Type          105668 non-null  object
 20  TYPE          0 non-null       object
dtypes: datetime64[ns](2), object(19)
memory usage: 17.7+ MB

In [34]:
#Split the column
split=df['Airport'].str.split(',',expand=True)
df['Airportlon']=split[0]
df['Airportlat']=split[1]

In [35]:
df.columns

Index(['URLS', 'City', 'Title', 'Price', 'Check_in', 'Check_Out', 'Rate',
       'Address', 'latlon', 'Score', 'Checkin_day', 'Checkout_day', 'Year',
       'Month', 'Day', 'Check_Month', 'lon', 'lat', 'Airport', 'Type', 'TYPE',
       'Airportlon', 'Airportlat'],
      dtype='object')

In [36]:
#Change the type for the coordinate column  
df["Airportlon"]=df["Airportlon"].astype(float)       
df["Airportlat"]=df["Airportlat"].astype(float)  
df["lat"]=df["lat"].astype(float)  
df["lon"]=df["lon"].astype(float)

In [37]:
pip install h3

Collecting h3
  Downloading h3-3.7.4-cp39-cp39-macosx_10_9_x86_64.whl (952 kB)
     |████████████████████████████████| 952 kB 973 kB/s eta 0:00:01
Installing collected packages: h3
Successfully installed h3-3.7.4
Note: you may need to restart the kernel to use updated packages.

In [38]:
import h3
#calculate the distance between the hotel and the airport 
df['Distance'] = df.apply(lambda row: h3.point_dist((row['Airportlon'], row['Airportlat']), (row['lon'], row['lat'])), axis=1)

In [39]:
df[['Title','Airportlat','Airportlon','lat','lon','Distance']]

,Title,Airportlat,Airportlon,lat,lon,Distance
0,جولدن ديون هوتل & سويت,46.7008,24.9637,46.802868,24.688253,32.314069
1,فندق لابيرلا,46.7008,24.9637,46.818461,24.794518,22.243547
2,فندق كارم الرياض Karim Hotel Riyadh,46.7008,24.9637,46.706097,24.754765,23.238700
4,Almakan Hotel 113,46.7008,24.9637,46.701175,24.662304,33.513723
5,فندق ريف الملز إنترناشونال,46.7008,24.9637,46.720798,24.659011,33.940005
...,...,...,...,...,...,...
164647,Kease A6 Al-Malqa Modern Royal Era,46.7008,24.9637,46.605492,24.819155,18.728266
164649,Kease B5-4 AlTawun Royal Touch - التعاون اللمس...,46.7008,24.9637,46.704736,24.774992,20.987097
164657,Kease A5-1 Al Tawun Royal Touch - التعاون اللم...,46.7008,24.9637,46.704736,24.774992,20.987097
164659,ال متعب سويتس الفلاح,46.7008,24.9637,46.702713,24.789867,19.330362
164663,Kease J9 Al Arid Black Diamond - العارض الالما...,46.7008,24.9637,46.628840,24.883417,11.504313

In [40]:
df.columns

Index(['URLS', 'City', 'Title', 'Price', 'Check_in', 'Check_Out', 'Rate',
       'Address', 'latlon', 'Score', 'Checkin_day', 'Checkout_day', 'Year',
       'Month', 'Day', 'Check_Month', 'lon', 'lat', 'Airport', 'Type', 'TYPE',
       'Airportlon', 'Airportlat', 'Distance'],
      dtype='object')

In [41]:
#Function to clean column  
import re
def cleantext(text):
    text = re.sub("\n", "", text)    
    return(text)
df['Score'].apply(cleantext)
df['Price']=df['Price'].str.replace(r'\D', '')

/var/folders/4g/tyxt36t547j_n6f0ft31746r0000gn/T/ipykernel_1325/919594126.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Price']=df['Price'].str.replace(r'\D', '')

In [42]:
df['Price']=df['Price'].astype(int)

In [43]:
#Multiply the Price by 3.75 to convert the Dollar to Saudi Riyal
df['Price'] = df['Price'].apply(lambda x: x*3.75)

In [44]:
df.head()

,URLS,City,Title,Price,Check_in,Check_Out,Rate,Address,latlon,Score,...,Day,Check_Month,lon,lat,Airport,Type,TYPE,Airportlon,Airportlat,Distance
0,https://www.booking.com/hotel/sa/golden-dune.a...,الرياض,جولدن ديون هوتل & سويت,360.00,2022-09-03,2022-09-04,['3 out of 5'],"['\n شارع سعود العثمان سعود سعود العثمان سعود,...","24.68825273,46.80286766",['\n8.1\n'],...,04,September,24.688253,46.802868,"24.9637, 46.7008",Room,NaN,24.9637,46.7008,32.314069
1,https://www.booking.com/hotel/sa/fndq-lbyrl-la...,الرياض,فندق لابيرلا,281.25,2022-09-03,2022-09-04,['3 out of 5'],"['\nفندق لابيرلا, 13216 الرياض, المملكة العربي...","24.79451790,46.81846073",['\n7.3\n'],...,04,September,24.794518,46.818461,"24.9637, 46.7008",Room,NaN,24.9637,46.7008,22.243547
2,https://www.booking.com/hotel/sa/krm-lryd-kare...,الرياض,فندق كارم الرياض Karim Hotel Riyadh,348.75,2022-09-03,2022-09-04,['4 out of 5'],"['\nPrince Mugrin Ibn Abdulaziz, An Nuzhah Dis...","24.75476486,46.70609703",['\n8.6\n'],...,04,September,24.754765,46.706097,"24.9637, 46.7008",Room,NaN,24.9637,46.7008,23.238700
4,https://www.booking.com/hotel/sa/myn-lmlq-107....,الرياض,Almakan Hotel 113,172.50,2022-09-03,2022-09-04,['3 out of 5'],"['\nKing Fahd Road العمرة -الملقا, 13521 الريا...","24.66230438,46.70117478",['\n6.6\n'],...,04,September,24.662304,46.701175,"24.9637, 46.7008",Studio,NaN,24.9637,46.7008,33.513723
5,https://www.booking.com/hotel/sa/tulip-inn-al-...,"الملاذ, الرياض",فندق ريف الملز إنترناشونال,135.00,2022-09-03,2022-09-04,['3 out of 5'],"['\nطريق الملك عبد العزيزخلف بنك سامبا , الملا...","24.65901078,46.72079802",['\n5.5\n'],...,04,September,24.659011,46.720798,"24.9637, 46.7008",Room,NaN,24.9637,46.7008,33.940005